

const dataMentoring = [
    {
        "id": 1,
        "mentee": "Eko Prasetyo",
        "Tanggal": "2024-11-01",
        "jam": "09:00",
        "title": "Advanced Programming",
        "materi": "Object-Oriented Programming",
        "Hasil": "Mengerti konsep dasar OOP",
        "todopast": "Menyelesaikan tugas inheritance",
        "todopre": "Mempelajari polymorphism",
        "feedback": "Perlu latihan lebih pada konsep inheritance",
        "status": "Selesai",
    },
    {
        "id": 2,
        "mentee": "Fajar Nugroho",
        "Tanggal": "2024-11-01",
        "jam": "10:30",
        "title": "Advanced Programming",
        "materi": "Data Structures",
        "Hasil": "Mengerti dasar linked list",
        "todopast": "Menyusun struktur linked list",
        "todopre": "Mempelajari binary tree",
        "feedback": "Perlu pemahaman lebih pada linked list",
        "status": "Belum Selesai",
    },
    {
        "id": 3,
        "mentee": "Gita Permata",
        "Tanggal": "2024-11-01",
        "jam": "13:00",
        "title": "Advanced Programming",
        "materi": "Algorithms",
        "Hasil": "Menyelesaikan algoritma sorting",
        "todopast": "Menyelesaikan tugas sorting",
        "todopre": "Mempelajari algoritma searching",
        "feedback": "Sudah cukup baik, lanjutkan ke tahap selanjutnya",
        "status": "Selesai",
    },
    {
        "id": 4,
        "mentee": "Hadi Santoso",
        "Tanggal": "2024-11-01",
        "jam": "14:30",
        "title": "Advanced Programming",
        "materi": "Software Engineering",
        "Hasil": "Memahami konsep SDLC",
        "todopast": "Membaca teori SDLC",
        "todopre": "Membuat diagram UML",
        "feedback": "Perlu pemahaman lebih pada tahap SDLC",
        "status": "Belum Selesai",
    },
    {
        "id": 5,
        "mentee": "Ika Sari",
        "Tanggal": "2024-11-01",
        "jam": "16:00",
        "title": "Advanced Programming",
        "materi": "Machine Learning",
        "Hasil": "Mengerti dasar machine learning",
        "todopast": "Menyelesaikan tugas regression",
        "todopre": "Mempelajari classification",
        "feedback": "Perlu latihan lebih pada regression",
        "status": "Belum Selesai",
    }
]

export { dataMentoring }